name = "newsnow"
pages_build_output_dir = "dist/output/public"
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "5e550118-cf89-4a45-a4ea-e28b3ca47634"
